[project]
<<<<<<< HEAD
name = "online-retail-clustring"
=======
name = "online-retail-clustering"
>>>>>>> 4e0582b (data exploration and cleaning)
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
<<<<<<< HEAD
=======
    "numpy>=2.2.4",
>>>>>>> 4e0582b (data exploration and cleaning)
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]
